import Breadcrumbs from "@/components/breadcrumbs/Breadcrumbs";
import GenericHeroSection from "@/components/home/hero/GenericHeroSection";
import GoogleMapSection from "@/components/home/map/GoogleMapSection";
import ContactSection from "@/components/sections/ContactSection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App ASdasd",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <GenericHeroSection
        className=" from-violet-500 to-violet-600"
        title="Kom i kontakt med oss"
        description={`Välkommen att kontakta Måleri Viskan!\nHar du några frågor, funderingar eller ett projekt planerat för din bostad eller ditt företag, tveka inte att höra av dig för att göra idé till verklighet.`}
        quoteButton
      />
      <Breadcrumbs />
      <ContactSection
        bg="from-white to-white text-black"
        linkColors="text-cyan-600 border-cyan-600"
        invertArrow={false}
      />
      <GoogleMapSection />
    </>
  );
};

export default page;
